version: 2
updates:

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "terraform"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
