version: "3.8"

services:
  terraform:
    build:
      dockerfile: devtools.Dockerfile
      target: tfswitch
    volumes:
      - .:/srv/src:z
      - ./.terraform.versions:/root/.terraform.versions:z
      - ${HOME}/.terraform.d:/root/.terraform.d:r
  tflint:
    image: ghcr.io/terraform-linters/tflint:latest@sha256:1ec926db4a400fdc620b55e5ff9c8ed15b7a4cc8b8fb70bd3cd0e0ab894d88e1
    volumes:
      - .:/srv/src
    working_dir: /srv/src
