validate target:
    hadolint {{ target }}.Dockerfile

image_tag := `git rev-parse HEAD`
docker_build_args := ""

build target:
    docker buildx build \
        --file {{ target }}.Dockerfile \
        --platform linux/amd64,linux/arm64 \
        --target main \
        --tag ghcr.io/nikitabarskov/{{ target }}:latest \
        --tag ghcr.io/nikitabarskov/{{ target }}:{{ image_tag }} \
        {{ docker_build_args }} \
        .

ci target: (build target)
