set dotenv-load
set unstable

default:
    just --list

configure:
    tofu init -backend=false

upgrade:
    tofu init -backend=false -upgrade

# fix auto-fixable issues
fix:
    tofu fmt -recursive .

validate:
    tofu fmt -check -recursive .
    tofu validate .

ci: configure validate

plan: validate
    spacectl stack local-preview --id dev
