version: "3.8"

services:
  dev:
    build:
      dockerfile: Dockerfile
      target: src
    volumes:
      - .:/srv/src:z
      - .next:/srv/src/.next
      - node_modules:/srv/src/node_modules
    command: "yarn next dev"
    ports:
      - "3000:3000"
  app:
    build:
      dockerfile: Dockerfile
      target: app
    ports:
      - "3000:3000"
volumes:
  node_modules:
  .next:
