on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory for the OpenTofu infrastructure"
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikitabarskov/base-ci:latest@sha256:7008e2ce96dec20eb40c079d77e2a261e1f5088ef708418e606f13e33f745aec
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      MISE_DATA_DIR: ~/.local/share/mise
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ${{ env.MISE_DATA_DIR }}
          key: ${{ runner.os }}-mise-${{ hashFiles('mise.lock') }}
          restore-keys: |
            ${{ runner.os }}-mise-
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ inputs.working-directory }}/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working-directory)) }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - run: |
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      - name: CI
        working-directory: ${{ inputs.working-directory }}
        run: |
          mise install
          just ci
