on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory for the OpenTofu infrastructure"
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikitabarskov/base-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      MISE_DATA_DIR: ~/.local/share/mise
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ${{ env.MISE_DATA_DIR }}
          key: ${{ runner.os }}-mise-${{ hashFiles('mise.lock') }}
          restore-keys: |
            ${{ runner.os }}-mise-
      - name: CI
        working-directory: ${{ inputs.working-directory }}
        run: |
          mise install
          just ci
