on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory for the OpenTofu infrastructure"
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikitabarskov/base-ci:latest@sha256:b2adf5199e4e35b22b6be422e990b2e4d468447baff173b4390ca40185bd60ac
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      MISE_DATA_DIR: ~/.local/share/mise
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ${{ env.MISE_DATA_DIR }}
          key: ${{ runner.os }}-mise-${{ hashFiles('mise.lock') }}
          restore-keys: |
            ${{ runner.os }}-mise-
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ inputs.working-directory }}/.terraform
          key:
            ${{ runner.os }}-terraform-${{
            hashFiles(format('{0}/.terraform.lock.hcl',
            inputs.working-directory)) }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - run: |
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      - name: CI
        working-directory: ${{ inputs.working-directory }}
        run: |
          mise install
          just ci
